

- name: Creates workdir directory
  file:
    path: "{{ substrate_node_workdir }}"
    state: directory

- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ substrate_node_workdir }}/docker-compose.yml"
    mode: "0644"

- name: Start service
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ substrate_node_workdir }}"

